name: CD Deployment

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'CI Run ID to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo (needed for azure/webapps-deploy action)
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Download artifact from CI workflow
    - name: Download CI artifact
      uses: actions/download-artifact@v4
      with:
        name: python-app-artifact   # must match artifact uploaded in CI
        path: python-app-${{ github.event.inputs.run_id }} # local folder to extract artifact into

    # 3️⃣ Login to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 4️⃣ Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: TaskManagerDemo   # your App Service name
        slot-name: 'production'
        package: './python-app-artifact'
